// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh2vmf4Q6HuHO0DLZqLJlvCsqj8ahDCeY',
    appId: '1:985880008727:web:970efef4d248dc445de452',
    messagingSenderId: '985880008727',
    projectId: 'rizer-demo',
    authDomain: 'rizer-demo.firebaseapp.com',
    storageBucket: 'rizer-demo.appspot.com',
    measurementId: 'G-D75HFLYVP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyTVKWrEVIIvf_ujSXIE7efZaWt6EPoIE',
    appId: '1:985880008727:android:6b8c010a4ec9c6de5de452',
    messagingSenderId: '985880008727',
    projectId: 'rizer-demo',
    storageBucket: 'rizer-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA90HXCp2nEQcuvmU0RSbdYpBiuF7cyh7A',
    appId: '1:985880008727:ios:5d718f6ca9b04fde5de452',
    messagingSenderId: '985880008727',
    projectId: 'rizer-demo',
    storageBucket: 'rizer-demo.appspot.com',
    androidClientId: '985880008727-l96pjrrqgksac7mula9ibsq6m6p2kram.apps.googleusercontent.com',
    iosClientId: '985880008727-8vdhoqhtcrnam6io0hcglriao2m3nilg.apps.googleusercontent.com',
    iosBundleId: 'com.amandesai.rizer',
  );
}
